export type IOwnerDataModel = {
    id: string;
    name: string;
    email?: string;
    description?: string;
    cover_url?: string;
    is_default: boolean;
    created_at: string;
    updated_at: string;
    id_country: string;
    legal_name: string;
    legal_form: string;
    phonenumber: string;
    birthdate: string;
    birth_place: string,
    marital_status: string,
    identity_card_type: string,
    identity_card_number: string,
    identity_card_expiry_date: string,
    address: string,
    municipality: string,
    street: string,
    profession: string,
    company_name: string,
    avg_monthly_income: number,
    payment_mode: string,
    banque: string,
    titulaireCompte: string
}