name: Deploy Development
concurrency:
  group: deploy-develop
  cancel-in-progress: true
on:
  push:
    branches:
      - develop
    paths-ignore:
      - .github/workflows/deploy_prod.yaml
      - .github/workflows/ci.yaml

jobs:
  build-and-deploy:
    name: Build And Deploy
    uses: Everest-Develop-Center/devops/.github/workflows/deploy-docker.yaml@v1.5
    with:
      app_name: katika-pro
      image_tag: develop
      context: dockerhub
      with_commit_image: false
      deploy_stage: develop
      deploy_port: 3011
      dns_name: katika-pro.dev-team-everest.xyz
      exposed_port: 3000

    secrets:
      registry: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
      ssh_port: ${{ secrets.EVE_DEV_SSH_PORT }}
      ssh_host: ${{ secrets.EVE_DEV_SERVER }}
      ssh_user: ${{ secrets.EVE_DEV_USER }}
      ssh_key: ${{ secrets.EVE_DEV_PRIVATE_KEY }}
      deploy_env: ${{ secrets.DEV_ENV }}
      build_env: ${{ secrets.DEV_ENV }}
